{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.groupName }}
    alb.ingress.kubernetes.io/group.order: "20"
    alb.ingress.kubernetes.io/transforms.users: |
      [{"type":"url-rewrite","urlRewriteConfig":{"rewrites":[{"regex":"^/api/users/?(.*)$","replace":"/users/$1"}]}}]
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: users
                port:
                  number: 80
{{- end }}