replicaCount: 2

image:
  repository: 482311061933.dkr.ecr.ap-south-1.amazonaws.com/orders
  tag: "39"

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

ingress:
  enabled: true
  groupName: production
